### ISSUE TITLE
null reference exception

### ISSUE THREAD

**Issue by ITFactoryAUT** [devbridge/AzurePowerTools#10]
Hello,
I would suggest to add a null check to the following:
`var config = System.Configuration.ConfigurationManager.GetSection("basicAuth");
            var basicAuth = (Configuration.BasicAuthenticationConfigurationSection)config;

            allowRedirects = basicAuth.AllowRedirects;
            allowLocal = basicAuth.AllowLocal;

            InitCredentials(basicAuth);
            InitExcludes(basicAuth);

            // Subscribe to the authenticate event to perform the authentication.
            context.AuthenticateRequest += AuthenticateUser;
            
            // Subscribe to the EndRequest event to issue the authentication challenge if necessary.
            context.EndRequest += IssueAuthenticationChallenge;`

In my case I didn´t had a config section named "basicAuth" but that is missing in your documentation, especially [https://www.devbridge.com/articles/basic-authentication-for-windows-azure-websites/](url)

Greetings
Nico

**Comment by mariusrybelis** [comment]
Hi Nico,

Thanks for your suggestion. Updated configuration loading is pushed with d5ec120

Marius
