### ISSUE TITLE
Possible Security Risk

### ISSUE THREAD

**Issue by Charles113** [devbridge/AzurePowerTools#15]
Thanks for this Module, this gave me some good ideas how to make a custom basic authentication module.

I have the following Recommendations:

use httpApp.CompleteRequest(); after ExtractBasicCredentials or ValidateCredentials failed. This prevents further code execution and "headers have already been sent" Exception.

activeUsers = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) // no need to put all userNames in lower case

#### Possible Security risk:
Don't use cookie with BasicAuthentication : 1; a client sending this cookie will bypass your authorization if i'm not mistaken.

Cheers

**Comment by mariusrybelis** [comment]
Charles thanks for your feedback.

I will incorporate CompleteRequest into the codebase. You can submit a pull request as well :)

The comparison of user names ignoring casing was done on purpose. We were debating about it for a while - both sides had some pros and cons. Eventually we decided that we will ignore casing. Maybe it is time to add ability to configure this piece? Feel free to submit a pull request.

This module is not intended to be used in production. The goal is to protect your test web site from bots and random people. So we decided to use a simple cookie check.

Marius

**Comment by mariusrybelis** [comment]
Changes to incorporate CompleteRequest were added in PR #16.

**Comment by vayachit** [comment]
@mariusrybelis Completing request early sends blank page when using excludes on static pages. Do you see this issue?
