### ISSUE TITLE
Restrict BasicAuthentication to specific locations

### ISSUE THREAD

**Issue by gavinharriss** [devbridge/AzurePowerTools#2]
I'm just wondering if it's possible to restrict Devbridge.BasicAuthentication to specific locations?

e.g.
```
  <location path="secret">
    <system.web>
      <authorization>
        <allow users="?" />
      </authorization>
    </system.web>
  </location>
```
Or perhaps you could give some guidance on what I'd need to change in your code?

Thanks for sharing!

**Comment by mariusrybelis** [comment]
Hi Gavin,

Currently you cannot specify location that you want to exclude/include. We found a commit (https://github.com/mlessard69/AzurePowerTools/commit/b97a4d61a357bc91f04e862b50ca5b79085eb778) by mlessard69 that allows to exclude specific URLs. We are planning to merge that commit into our code in a couple days.

**Comment by gavinharriss** [comment]
Thanks for that - much appreciated. Looks like nice easy code I can simply adapt to include specific urls instead of exclude. I'm a little time poor at the moment, but if I get a chance to adapt the code I'll make a pull request so you can include it in the solution if you'd like. Always nice to contribute back :)

**Comment by mariusrybelis** [comment]
Hi Gavin,

I just pushed an updated version. New version adds ability to configure what request should be excluded from authentication. I took mlessard69's work and added additional functionality. https://github.com/devbridge/AzurePowerTools has info how to use new configuration.
You can use any valid RegEx for url. So you should be able to configure authentication only on specific URLs either by negating exclude rule or by adding several exclude rules.

**Comment by gavinharriss** [comment]
Much appreciated - thank you :)
